typography_spectrum: 0.8250186883378774
color:
  brandStrength: 0.10327262012287974
  lightness: 0.21185195934958756
  saturation: 0.46338661666959524
  rhythmicContrast: 0.7799580714199692
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.4841199894435704
author:
  name: Renatho Siqueira
  email: renatho@renatho.com.br
  url: www.renatho.mba
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fffdac77-d234-42b2-b6b7-d21a651ddfa2.png
name: Renatho Siqueira
title: Renatho.MBA
description: 'Marketing, Comunicação, Comportamento e Sociedade'
